# Generated by Django 4.1.7 on 2023-03-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todocore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
